apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-mongo-pvc
  namespace: app
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources: { requests: { storage: 5Gi } }
---
apiVersion: v1
kind: Service
metadata:
  name: user-mongo
  namespace: app
spec:
  selector: { app: user-mongo }
  ports:
    - name: mongo
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mongo
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: user-mongo } }
  template:
    metadata: { labels: { app: user-mongo } }
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports: [ { containerPort: 27017 } ]
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom: { secretKeyRef: { name: mongo-secret, key: MONGO_INITDB_ROOT_USERNAME } }
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom: { secretKeyRef: { name: mongo-secret, key: MONGO_INITDB_ROOT_PASSWORD } }
          volumeMounts:
            - name: data
              mountPath: /data/db
          readinessProbe:
            exec: { command: ["mongosh","--quiet","--eval","db.adminCommand('ping')"] }
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: data
          persistentVolumeClaim: { claimName: user-mongo-pvc }