apiVersion: v1
kind: Secret
metadata:
  name: question-pg-secret
  namespace: app
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: questiondb
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: app
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: mongoadmin
  MONGO_INITDB_ROOT_PASSWORD: mongopass