apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: matching-service } }
  template:
    metadata: { labels: { app: matching-service } }
    spec:
      containers:
        - name: matching
          image: asia-southeast1-docker.pkg.dev/peerprep2/backend-microservices/matching-service:dev    # built into minikube
          ports: [{ containerPort: 8080 }]
          resources:  
            limits:
              memory: "1Gi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: matching-service
  namespace: app
spec:
  selector: { app: matching-service }
  ports:
    - port: 80
      targetPort: 8080
