apiVersion: apps/v1
kind: Deployment
metadata:
  name: collab-service
  namespace: app
spec:
  replicas: 1
  selector: { matchLabels: { app: collab-service } }
  template:
    metadata: { labels: { app: collab-service } }
    spec:
      containers:
        - name: collab
          image: asia-southeast1-docker.pkg.dev/peerprep2/backend-microservices/collab-service:dev      # built into minikube
          ports: [{ containerPort: 4000 }]
          resources:  
            limits:
              memory: "1Gi"
              cpu: "250m"
          envFrom:
            - secretRef:
                name: collab-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: collab-service
  namespace: app
spec:
  selector: { app: collab-service }
  ports:
    - port: 80
      targetPort: 4000
